# .github/workflows/firebase-hosting.yml
name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # Or the branch you want to deploy

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - run: npm install  # Install dependencies

    # - run: npm run build  # Build your project (adjust according to your build command)

    - uses: FirebaseExtended/action-hosting-deploy@v0  # Use the Firebase GitHub Action
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        channelId: live  # Deploy to live channel
